categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by %s
theme: Theme - %s
rss_feed: RSS Feed
category: Category
tag: Tag
site_visitors: Visitors
page_views: Views
friends: Friends
search_placeholder: Tell Aichan what you are looking for

post:
  word_count: Word count
  read_time: Reading time
  minutes: min
  reward: Donate
  sticky: Sticky
  copyright_title: Copyright
  copyright_content: Unless otherwise noted, all the blogs are licensed under CC BY-NC 4.0.

lock:
  lock_info: Please enter password
  lock_error: Incorrect password, please try again
  confirm_text: Ok
  cancel_text: Cancel
